FROM python:3.11-slim

WORKDIR /app

# Копирование requirements и установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Копирование файлов приложения
COPY . .

# Открываем порт для Flask
EXPOSE 5000

# Запуск Flask приложения в режиме разработки
CMD ["python", "main.py"]

