FROM python:3.11-slim

WORKDIR /app

# Установка зависимостей
RUN pip install --no-cache-dir flask

# Копирование файлов приложения
COPY . .

# Открываем порт для Flask
EXPOSE 5000

# Запуск Flask приложения в режиме разработки
CMD ["python", "main.py"]

